// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package applicationproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestHeader struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type MasterRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MasterRequest) Reset()         { *m = MasterRequest{} }
func (m *MasterRequest) String() string { return proto.CompactTextString(m) }
func (*MasterRequest) ProtoMessage()    {}
func (*MasterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *MasterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterRequest.Unmarshal(m, b)
}
func (m *MasterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterRequest.Marshal(b, m, deterministic)
}
func (m *MasterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterRequest.Merge(m, src)
}
func (m *MasterRequest) XXX_Size() int {
	return xxx_messageInfo_MasterRequest.Size(m)
}
func (m *MasterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MasterRequest proto.InternalMessageInfo

func (m *MasterRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type Item struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alignment            string   `protobuf:"bytes,3,opt,name=alignment,proto3" json:"alignment,omitempty"`
	Sortable             bool     `protobuf:"varint,4,opt,name=sortable,proto3" json:"sortable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetAlignment() string {
	if m != nil {
		return m.Alignment
	}
	return ""
}

func (m *Item) GetSortable() bool {
	if m != nil {
		return m.Sortable
	}
	return false
}

type DataField struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataField) Reset()         { *m = DataField{} }
func (m *DataField) String() string { return proto.CompactTextString(m) }
func (*DataField) ProtoMessage()    {}
func (*DataField) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *DataField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataField.Unmarshal(m, b)
}
func (m *DataField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataField.Marshal(b, m, deterministic)
}
func (m *DataField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataField.Merge(m, src)
}
func (m *DataField) XXX_Size() int {
	return xxx_messageInfo_DataField.Size(m)
}
func (m *DataField) XXX_DiscardUnknown() {
	xxx_messageInfo_DataField.DiscardUnknown(m)
}

var xxx_messageInfo_DataField proto.InternalMessageInfo

func (m *DataField) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DataField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataField) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Rows struct {
	Row                  map[string]string `protobuf:"bytes,1,rep,name=Row,proto3" json:"Row,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Rows) Reset()         { *m = Rows{} }
func (m *Rows) String() string { return proto.CompactTextString(m) }
func (*Rows) ProtoMessage()    {}
func (*Rows) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *Rows) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rows.Unmarshal(m, b)
}
func (m *Rows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rows.Marshal(b, m, deterministic)
}
func (m *Rows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rows.Merge(m, src)
}
func (m *Rows) XXX_Size() int {
	return xxx_messageInfo_Rows.Size(m)
}
func (m *Rows) XXX_DiscardUnknown() {
	xxx_messageInfo_Rows.DiscardUnknown(m)
}

var xxx_messageInfo_Rows proto.InternalMessageInfo

func (m *Rows) GetRow() map[string]string {
	if m != nil {
		return m.Row
	}
	return nil
}

type ApplicationRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ApplicationRequest) Reset()         { *m = ApplicationRequest{} }
func (m *ApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*ApplicationRequest) ProtoMessage()    {}
func (*ApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *ApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationRequest.Unmarshal(m, b)
}
func (m *ApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationRequest.Marshal(b, m, deterministic)
}
func (m *ApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationRequest.Merge(m, src)
}
func (m *ApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_ApplicationRequest.Size(m)
}
func (m *ApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationRequest proto.InternalMessageInfo

func (m *ApplicationRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ApplicationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ApplicationContentRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Query                string         `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ApplicationContentRequest) Reset()         { *m = ApplicationContentRequest{} }
func (m *ApplicationContentRequest) String() string { return proto.CompactTextString(m) }
func (*ApplicationContentRequest) ProtoMessage()    {}
func (*ApplicationContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *ApplicationContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationContentRequest.Unmarshal(m, b)
}
func (m *ApplicationContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationContentRequest.Marshal(b, m, deterministic)
}
func (m *ApplicationContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationContentRequest.Merge(m, src)
}
func (m *ApplicationContentRequest) XXX_Size() int {
	return xxx_messageInfo_ApplicationContentRequest.Size(m)
}
func (m *ApplicationContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationContentRequest proto.InternalMessageInfo

func (m *ApplicationContentRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ApplicationContentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApplicationContentRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type MasterResponse struct {
	StatusCode           int32                `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *MasterResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MasterResponse) Reset()         { *m = MasterResponse{} }
func (m *MasterResponse) String() string { return proto.CompactTextString(m) }
func (*MasterResponse) ProtoMessage()    {}
func (*MasterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *MasterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterResponse.Unmarshal(m, b)
}
func (m *MasterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterResponse.Marshal(b, m, deterministic)
}
func (m *MasterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterResponse.Merge(m, src)
}
func (m *MasterResponse) XXX_Size() int {
	return xxx_messageInfo_MasterResponse.Size(m)
}
func (m *MasterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MasterResponse proto.InternalMessageInfo

func (m *MasterResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *MasterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MasterResponse) GetData() *MasterResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type MasterResponse_Data struct {
	Username             string       `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Avatar               string       `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	FullName             string       `protobuf:"bytes,4,opt,name=fullName,proto3" json:"fullName,omitempty"`
	CustomerName         string       `protobuf:"bytes,5,opt,name=customerName,proto3" json:"customerName,omitempty"`
	Dashboards           []*DataField `protobuf:"bytes,6,rep,name=dashboards,proto3" json:"dashboards,omitempty"`
	Applications         []*DataField `protobuf:"bytes,7,rep,name=applications,proto3" json:"applications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MasterResponse_Data) Reset()         { *m = MasterResponse_Data{} }
func (m *MasterResponse_Data) String() string { return proto.CompactTextString(m) }
func (*MasterResponse_Data) ProtoMessage()    {}
func (*MasterResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7, 0}
}

func (m *MasterResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterResponse_Data.Unmarshal(m, b)
}
func (m *MasterResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterResponse_Data.Marshal(b, m, deterministic)
}
func (m *MasterResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterResponse_Data.Merge(m, src)
}
func (m *MasterResponse_Data) XXX_Size() int {
	return xxx_messageInfo_MasterResponse_Data.Size(m)
}
func (m *MasterResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_MasterResponse_Data proto.InternalMessageInfo

func (m *MasterResponse_Data) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MasterResponse_Data) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *MasterResponse_Data) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *MasterResponse_Data) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

func (m *MasterResponse_Data) GetDashboards() []*DataField {
	if m != nil {
		return m.Dashboards
	}
	return nil
}

func (m *MasterResponse_Data) GetApplications() []*DataField {
	if m != nil {
		return m.Applications
	}
	return nil
}

type ApplicationResponse struct {
	StatusCode           int32                     `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *ApplicationResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ApplicationResponse) Reset()         { *m = ApplicationResponse{} }
func (m *ApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*ApplicationResponse) ProtoMessage()    {}
func (*ApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *ApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationResponse.Unmarshal(m, b)
}
func (m *ApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationResponse.Marshal(b, m, deterministic)
}
func (m *ApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationResponse.Merge(m, src)
}
func (m *ApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_ApplicationResponse.Size(m)
}
func (m *ApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationResponse proto.InternalMessageInfo

func (m *ApplicationResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ApplicationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ApplicationResponse) GetData() *ApplicationResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type ApplicationResponse_Data struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns              []*Item      `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	RelatedRecords       []*DataField `protobuf:"bytes,3,rep,name=relatedRecords,proto3" json:"relatedRecords,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ApplicationResponse_Data) Reset()         { *m = ApplicationResponse_Data{} }
func (m *ApplicationResponse_Data) String() string { return proto.CompactTextString(m) }
func (*ApplicationResponse_Data) ProtoMessage()    {}
func (*ApplicationResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8, 0}
}

func (m *ApplicationResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationResponse_Data.Unmarshal(m, b)
}
func (m *ApplicationResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationResponse_Data.Marshal(b, m, deterministic)
}
func (m *ApplicationResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationResponse_Data.Merge(m, src)
}
func (m *ApplicationResponse_Data) XXX_Size() int {
	return xxx_messageInfo_ApplicationResponse_Data.Size(m)
}
func (m *ApplicationResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationResponse_Data proto.InternalMessageInfo

func (m *ApplicationResponse_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApplicationResponse_Data) GetColumns() []*Item {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *ApplicationResponse_Data) GetRelatedRecords() []*DataField {
	if m != nil {
		return m.RelatedRecords
	}
	return nil
}

type ApplicationContentResponse struct {
	StatusCode           int32                            `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *ApplicationContentResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ApplicationContentResponse) Reset()         { *m = ApplicationContentResponse{} }
func (m *ApplicationContentResponse) String() string { return proto.CompactTextString(m) }
func (*ApplicationContentResponse) ProtoMessage()    {}
func (*ApplicationContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *ApplicationContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationContentResponse.Unmarshal(m, b)
}
func (m *ApplicationContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationContentResponse.Marshal(b, m, deterministic)
}
func (m *ApplicationContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationContentResponse.Merge(m, src)
}
func (m *ApplicationContentResponse) XXX_Size() int {
	return xxx_messageInfo_ApplicationContentResponse.Size(m)
}
func (m *ApplicationContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationContentResponse proto.InternalMessageInfo

func (m *ApplicationContentResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ApplicationContentResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ApplicationContentResponse) GetData() *ApplicationContentResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type ApplicationContentResponse_Data struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns              []*Item  `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows                 []*Rows  `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationContentResponse_Data) Reset()         { *m = ApplicationContentResponse_Data{} }
func (m *ApplicationContentResponse_Data) String() string { return proto.CompactTextString(m) }
func (*ApplicationContentResponse_Data) ProtoMessage()    {}
func (*ApplicationContentResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9, 0}
}

func (m *ApplicationContentResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationContentResponse_Data.Unmarshal(m, b)
}
func (m *ApplicationContentResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationContentResponse_Data.Marshal(b, m, deterministic)
}
func (m *ApplicationContentResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationContentResponse_Data.Merge(m, src)
}
func (m *ApplicationContentResponse_Data) XXX_Size() int {
	return xxx_messageInfo_ApplicationContentResponse_Data.Size(m)
}
func (m *ApplicationContentResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationContentResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationContentResponse_Data proto.InternalMessageInfo

func (m *ApplicationContentResponse_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApplicationContentResponse_Data) GetColumns() []*Item {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *ApplicationContentResponse_Data) GetRows() []*Rows {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestHeader)(nil), "applicationproto.RequestHeader")
	proto.RegisterType((*MasterRequest)(nil), "applicationproto.MasterRequest")
	proto.RegisterType((*Item)(nil), "applicationproto.Item")
	proto.RegisterType((*DataField)(nil), "applicationproto.DataField")
	proto.RegisterType((*Rows)(nil), "applicationproto.Rows")
	proto.RegisterMapType((map[string]string)(nil), "applicationproto.Rows.RowEntry")
	proto.RegisterType((*ApplicationRequest)(nil), "applicationproto.ApplicationRequest")
	proto.RegisterType((*ApplicationContentRequest)(nil), "applicationproto.ApplicationContentRequest")
	proto.RegisterType((*MasterResponse)(nil), "applicationproto.MasterResponse")
	proto.RegisterType((*MasterResponse_Data)(nil), "applicationproto.MasterResponse.Data")
	proto.RegisterType((*ApplicationResponse)(nil), "applicationproto.ApplicationResponse")
	proto.RegisterType((*ApplicationResponse_Data)(nil), "applicationproto.ApplicationResponse.Data")
	proto.RegisterType((*ApplicationContentResponse)(nil), "applicationproto.ApplicationContentResponse")
	proto.RegisterType((*ApplicationContentResponse_Data)(nil), "applicationproto.ApplicationContentResponse.Data")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 643 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x6f, 0x4f, 0xd4, 0x4e,
	0x10, 0x4e, 0x7b, 0xe5, 0x80, 0x39, 0x8e, 0x90, 0xf9, 0xfd, 0x24, 0xf5, 0x34, 0x72, 0x69, 0x24,
	0x21, 0x68, 0x2e, 0x82, 0x89, 0x7f, 0x13, 0x8d, 0x41, 0x04, 0x5f, 0x68, 0xe2, 0x7e, 0x83, 0xa5,
	0x1d, 0xa1, 0xa1, 0xed, 0x1e, 0xbb, 0x5b, 0x4e, 0xde, 0x18, 0xbf, 0x82, 0xaf, 0xfc, 0x00, 0x7e,
	0x09, 0x3f, 0x9a, 0x2f, 0xcd, 0x6e, 0x5b, 0x68, 0xb9, 0xc3, 0xc3, 0x9c, 0xbe, 0x69, 0x3a, 0xb3,
	0x33, 0xf3, 0xcc, 0x3c, 0xf3, 0xec, 0x42, 0x57, 0x91, 0x3c, 0x8d, 0x43, 0x1a, 0x0c, 0xa5, 0xd0,
	0x02, 0x57, 0xf8, 0x70, 0x98, 0xc4, 0x21, 0xd7, 0xb1, 0xc8, 0xac, 0x27, 0x58, 0x87, 0x2e, 0xa3,
	0x93, 0x9c, 0x94, 0xde, 0x27, 0x1e, 0x91, 0xc4, 0xff, 0x61, 0x4e, 0x8b, 0x63, 0xca, 0x7c, 0xa7,
	0xef, 0x6c, 0x2c, 0xb2, 0xc2, 0x08, 0xf6, 0xa1, 0xfb, 0x8e, 0x2b, 0x4d, 0xb2, 0x0c, 0xc6, 0xc7,
	0xd0, 0x3e, 0xb2, 0x09, 0x36, 0xae, 0xb3, 0xbd, 0x36, 0xb8, 0x5c, 0x7a, 0xd0, 0xa8, 0xcb, 0xca,
	0xf0, 0x20, 0x02, 0xef, 0xad, 0xa6, 0x14, 0x97, 0xc1, 0x8d, 0x23, 0x9b, 0x3c, 0xc7, 0xdc, 0x38,
	0x42, 0x04, 0x2f, 0xe3, 0x29, 0xf9, 0xae, 0x85, 0xb5, 0xff, 0x78, 0x1b, 0x16, 0x79, 0x12, 0x1f,
	0x66, 0x29, 0x65, 0xda, 0x6f, 0xd9, 0x83, 0x0b, 0x07, 0xf6, 0x60, 0x41, 0x09, 0xa9, 0xf9, 0x41,
	0x42, 0xbe, 0xd7, 0x77, 0x36, 0x16, 0xd8, 0xb9, 0x1d, 0x7c, 0x80, 0xc5, 0xd7, 0x5c, 0xf3, 0x37,
	0x31, 0x25, 0xd1, 0xb5, 0xa0, 0xfa, 0xd0, 0x89, 0x48, 0x85, 0x32, 0x1e, 0x9a, 0x01, 0x4a, 0xb0,
	0xba, 0x2b, 0x38, 0x01, 0x8f, 0x89, 0x91, 0xc2, 0x2d, 0x68, 0x31, 0x31, 0xf2, 0x9d, 0x7e, 0xeb,
	0x8a, 0xb1, 0xc5, 0x48, 0x99, 0xcf, 0x6e, 0xa6, 0xe5, 0x19, 0x33, 0xb1, 0xbd, 0x47, 0xb0, 0x50,
	0x39, 0x70, 0x05, 0x5a, 0xc7, 0x74, 0x56, 0xb2, 0x6b, 0x7e, 0x0d, 0xe3, 0xa7, 0x3c, 0xc9, 0xab,
	0x7e, 0x0a, 0xe3, 0x99, 0xfb, 0xc4, 0x09, 0x38, 0xe0, 0xab, 0x8b, 0xf2, 0xb3, 0x52, 0x3f, 0x69,
	0xee, 0xe0, 0x33, 0xdc, 0xac, 0x41, 0xec, 0x88, 0x4c, 0x53, 0xa6, 0xff, 0x05, 0x92, 0x19, 0xf3,
	0x24, 0x27, 0x79, 0x56, 0x72, 0x5b, 0x18, 0xc1, 0x97, 0x16, 0x2c, 0x57, 0xca, 0x52, 0x43, 0x91,
	0x29, 0xc2, 0x3b, 0x00, 0x4a, 0x73, 0x9d, 0xab, 0x1d, 0x11, 0x51, 0xb9, 0xb6, 0x9a, 0x07, 0x7d,
	0x98, 0x4f, 0x49, 0x29, 0x7e, 0x58, 0xd5, 0xaf, 0x4c, 0x7c, 0x0a, 0x5e, 0xc4, 0x35, 0xb7, 0x08,
	0x9d, 0xed, 0xf5, 0xf1, 0x6e, 0x9b, 0x48, 0x03, 0x23, 0x11, 0x66, 0x53, 0x7a, 0x3f, 0x1d, 0xf0,
	0x8c, 0x69, 0x54, 0x95, 0x2b, 0x92, 0xb5, 0xf6, 0xcf, 0x6d, 0x5c, 0x85, 0x36, 0x3f, 0xe5, 0x9a,
	0xcb, 0x72, 0x86, 0xd2, 0x32, 0x39, 0x1f, 0xf3, 0x24, 0x79, 0x6f, 0x72, 0xbc, 0x22, 0xa7, 0xb2,
	0x31, 0x80, 0xa5, 0x30, 0x57, 0x5a, 0xa4, 0x24, 0xed, 0xf9, 0x9c, 0x3d, 0x6f, 0xf8, 0xf0, 0x39,
	0x40, 0xc4, 0xd5, 0xd1, 0x81, 0xe0, 0x32, 0x52, 0x7e, 0xdb, 0x2a, 0xeb, 0xd6, 0x78, 0xf7, 0xe7,
	0x8a, 0x66, 0xb5, 0x70, 0x7c, 0x09, 0x4b, 0xb5, 0x48, 0xe5, 0xcf, 0x4f, 0x4f, 0x6f, 0x24, 0x04,
	0xdf, 0x5d, 0xf8, 0xaf, 0x21, 0xb3, 0x99, 0xf7, 0xf0, 0xa2, 0xb1, 0x87, 0xcd, 0xf1, 0x56, 0x26,
	0xc0, 0xd5, 0x97, 0xf1, 0xb5, 0x5a, 0x46, 0xa5, 0x23, 0xa7, 0xa6, 0xa3, 0x07, 0x30, 0x1f, 0x8a,
	0x24, 0x4f, 0x33, 0xe5, 0xbb, 0x76, 0xd4, 0xd5, 0xf1, 0xfa, 0xe6, 0x85, 0x61, 0x55, 0x18, 0xee,
	0xc0, 0xb2, 0xa4, 0x84, 0x6b, 0x8a, 0x18, 0x85, 0xc2, 0x50, 0xdc, 0x9a, 0xce, 0xd1, 0xa5, 0x94,
	0xe0, 0x9b, 0x0b, 0xbd, 0x49, 0x37, 0x65, 0x66, 0xb2, 0x76, 0x1b, 0x64, 0x6d, 0xfd, 0x96, 0xac,
	0x4b, 0xa8, 0x75, 0xce, 0x3e, 0xfd, 0x55, 0xca, 0x36, 0xc1, 0x93, 0x62, 0x54, 0x11, 0xb5, 0x3a,
	0xf9, 0x95, 0x63, 0x36, 0x66, 0xfb, 0x87, 0x0b, 0x9d, 0x5a, 0x8f, 0xc8, 0xa0, 0xbb, 0x47, 0xba,
	0xb8, 0x6a, 0xb6, 0xa5, 0xb5, 0xab, 0x2f, 0xa2, 0x7d, 0x3c, 0x7a, 0xfd, 0x69, 0x37, 0x15, 0x39,
	0xe0, 0x1e, 0xe9, 0x1a, 0x8a, 0x2d, 0x7c, 0x77, 0x8a, 0xb2, 0x8a, 0xea, 0xeb, 0xd7, 0xd2, 0x1f,
	0x4a, 0xb8, 0xd1, 0x84, 0x28, 0xc9, 0xc6, 0x7b, 0xd7, 0x5b, 0x49, 0x01, 0x76, 0xff, 0x4f, 0xf6,
	0x77, 0xd0, 0xb6, 0x11, 0x0f, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x16, 0xa2, 0x00, 0xf3, 0xa7,
	0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApplicationClient is the client API for Application service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApplicationClient interface {
	GetMasterData(ctx context.Context, in *MasterRequest, opts ...grpc.CallOption) (*MasterResponse, error)
	GetApplicationData(ctx context.Context, in *ApplicationRequest, opts ...grpc.CallOption) (*ApplicationResponse, error)
	GetApplicationContent(ctx context.Context, in *ApplicationContentRequest, opts ...grpc.CallOption) (*ApplicationContentResponse, error)
}

type applicationClient struct {
	cc *grpc.ClientConn
}

func NewApplicationClient(cc *grpc.ClientConn) ApplicationClient {
	return &applicationClient{cc}
}

func (c *applicationClient) GetMasterData(ctx context.Context, in *MasterRequest, opts ...grpc.CallOption) (*MasterResponse, error) {
	out := new(MasterResponse)
	err := c.cc.Invoke(ctx, "/applicationproto.Application/GetMasterData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) GetApplicationData(ctx context.Context, in *ApplicationRequest, opts ...grpc.CallOption) (*ApplicationResponse, error) {
	out := new(ApplicationResponse)
	err := c.cc.Invoke(ctx, "/applicationproto.Application/GetApplicationData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) GetApplicationContent(ctx context.Context, in *ApplicationContentRequest, opts ...grpc.CallOption) (*ApplicationContentResponse, error) {
	out := new(ApplicationContentResponse)
	err := c.cc.Invoke(ctx, "/applicationproto.Application/GetApplicationContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicationServer is the server API for Application service.
type ApplicationServer interface {
	GetMasterData(context.Context, *MasterRequest) (*MasterResponse, error)
	GetApplicationData(context.Context, *ApplicationRequest) (*ApplicationResponse, error)
	GetApplicationContent(context.Context, *ApplicationContentRequest) (*ApplicationContentResponse, error)
}

// UnimplementedApplicationServer can be embedded to have forward compatible implementations.
type UnimplementedApplicationServer struct {
}

func (*UnimplementedApplicationServer) GetMasterData(ctx context.Context, req *MasterRequest) (*MasterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMasterData not implemented")
}
func (*UnimplementedApplicationServer) GetApplicationData(ctx context.Context, req *ApplicationRequest) (*ApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplicationData not implemented")
}
func (*UnimplementedApplicationServer) GetApplicationContent(ctx context.Context, req *ApplicationContentRequest) (*ApplicationContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplicationContent not implemented")
}

func RegisterApplicationServer(s *grpc.Server, srv ApplicationServer) {
	s.RegisterService(&_Application_serviceDesc, srv)
}

func _Application_GetMasterData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MasterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).GetMasterData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/applicationproto.Application/GetMasterData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).GetMasterData(ctx, req.(*MasterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_GetApplicationData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).GetApplicationData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/applicationproto.Application/GetApplicationData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).GetApplicationData(ctx, req.(*ApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_GetApplicationContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).GetApplicationContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/applicationproto.Application/GetApplicationContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).GetApplicationContent(ctx, req.(*ApplicationContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Application_serviceDesc = grpc.ServiceDesc{
	ServiceName: "applicationproto.Application",
	HandlerType: (*ApplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMasterData",
			Handler:    _Application_GetMasterData_Handler,
		},
		{
			MethodName: "GetApplicationData",
			Handler:    _Application_GetApplicationData_Handler,
		},
		{
			MethodName: "GetApplicationContent",
			Handler:    _Application_GetApplicationContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
