// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package applicationproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestHeader struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Item struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName          string   `protobuf:"bytes,3,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Alignment            string   `protobuf:"bytes,4,opt,name=alignment,proto3" json:"alignment,omitempty"`
	Sortable             bool     `protobuf:"varint,5,opt,name=sortable,proto3" json:"sortable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Item) GetAlignment() string {
	if m != nil {
		return m.Alignment
	}
	return ""
}

func (m *Item) GetSortable() bool {
	if m != nil {
		return m.Sortable
	}
	return false
}

type DataField struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataField) Reset()         { *m = DataField{} }
func (m *DataField) String() string { return proto.CompactTextString(m) }
func (*DataField) ProtoMessage()    {}
func (*DataField) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *DataField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataField.Unmarshal(m, b)
}
func (m *DataField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataField.Marshal(b, m, deterministic)
}
func (m *DataField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataField.Merge(m, src)
}
func (m *DataField) XXX_Size() int {
	return xxx_messageInfo_DataField.Size(m)
}
func (m *DataField) XXX_DiscardUnknown() {
	xxx_messageInfo_DataField.DiscardUnknown(m)
}

var xxx_messageInfo_DataField proto.InternalMessageInfo

func (m *DataField) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DataField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataField) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Rows struct {
	Row                  map[string]string `protobuf:"bytes,1,rep,name=Row,proto3" json:"Row,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Rows) Reset()         { *m = Rows{} }
func (m *Rows) String() string { return proto.CompactTextString(m) }
func (*Rows) ProtoMessage()    {}
func (*Rows) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *Rows) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rows.Unmarshal(m, b)
}
func (m *Rows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rows.Marshal(b, m, deterministic)
}
func (m *Rows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rows.Merge(m, src)
}
func (m *Rows) XXX_Size() int {
	return xxx_messageInfo_Rows.Size(m)
}
func (m *Rows) XXX_DiscardUnknown() {
	xxx_messageInfo_Rows.DiscardUnknown(m)
}

var xxx_messageInfo_Rows proto.InternalMessageInfo

func (m *Rows) GetRow() map[string]string {
	if m != nil {
		return m.Row
	}
	return nil
}

type MasterDataRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MasterDataRequest) Reset()         { *m = MasterDataRequest{} }
func (m *MasterDataRequest) String() string { return proto.CompactTextString(m) }
func (*MasterDataRequest) ProtoMessage()    {}
func (*MasterDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *MasterDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterDataRequest.Unmarshal(m, b)
}
func (m *MasterDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterDataRequest.Marshal(b, m, deterministic)
}
func (m *MasterDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterDataRequest.Merge(m, src)
}
func (m *MasterDataRequest) XXX_Size() int {
	return xxx_messageInfo_MasterDataRequest.Size(m)
}
func (m *MasterDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MasterDataRequest proto.InternalMessageInfo

func (m *MasterDataRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type DataRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DataRequest) Reset()         { *m = DataRequest{} }
func (m *DataRequest) String() string { return proto.CompactTextString(m) }
func (*DataRequest) ProtoMessage()    {}
func (*DataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *DataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequest.Unmarshal(m, b)
}
func (m *DataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequest.Marshal(b, m, deterministic)
}
func (m *DataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequest.Merge(m, src)
}
func (m *DataRequest) XXX_Size() int {
	return xxx_messageInfo_DataRequest.Size(m)
}
func (m *DataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequest proto.InternalMessageInfo

func (m *DataRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DataRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ApplicationContentRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Query                string         `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ApplicationContentRequest) Reset()         { *m = ApplicationContentRequest{} }
func (m *ApplicationContentRequest) String() string { return proto.CompactTextString(m) }
func (*ApplicationContentRequest) ProtoMessage()    {}
func (*ApplicationContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *ApplicationContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationContentRequest.Unmarshal(m, b)
}
func (m *ApplicationContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationContentRequest.Marshal(b, m, deterministic)
}
func (m *ApplicationContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationContentRequest.Merge(m, src)
}
func (m *ApplicationContentRequest) XXX_Size() int {
	return xxx_messageInfo_ApplicationContentRequest.Size(m)
}
func (m *ApplicationContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationContentRequest proto.InternalMessageInfo

func (m *ApplicationContentRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ApplicationContentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApplicationContentRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type ReferencedContentRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ids                  []int32        `protobuf:"varint,3,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReferencedContentRequest) Reset()         { *m = ReferencedContentRequest{} }
func (m *ReferencedContentRequest) String() string { return proto.CompactTextString(m) }
func (*ReferencedContentRequest) ProtoMessage()    {}
func (*ReferencedContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *ReferencedContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferencedContentRequest.Unmarshal(m, b)
}
func (m *ReferencedContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferencedContentRequest.Marshal(b, m, deterministic)
}
func (m *ReferencedContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferencedContentRequest.Merge(m, src)
}
func (m *ReferencedContentRequest) XXX_Size() int {
	return xxx_messageInfo_ReferencedContentRequest.Size(m)
}
func (m *ReferencedContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferencedContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReferencedContentRequest proto.InternalMessageInfo

func (m *ReferencedContentRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ReferencedContentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReferencedContentRequest) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type MasterDataResponse struct {
	StatusCode           int32                    `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *MasterDataResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MasterDataResponse) Reset()         { *m = MasterDataResponse{} }
func (m *MasterDataResponse) String() string { return proto.CompactTextString(m) }
func (*MasterDataResponse) ProtoMessage()    {}
func (*MasterDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *MasterDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterDataResponse.Unmarshal(m, b)
}
func (m *MasterDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterDataResponse.Marshal(b, m, deterministic)
}
func (m *MasterDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterDataResponse.Merge(m, src)
}
func (m *MasterDataResponse) XXX_Size() int {
	return xxx_messageInfo_MasterDataResponse.Size(m)
}
func (m *MasterDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MasterDataResponse proto.InternalMessageInfo

func (m *MasterDataResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *MasterDataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MasterDataResponse) GetData() *MasterDataResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type MasterDataResponse_Data struct {
	Username             string       `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Avatar               string       `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	FullName             string       `protobuf:"bytes,4,opt,name=fullName,proto3" json:"fullName,omitempty"`
	CustomerName         string       `protobuf:"bytes,5,opt,name=customerName,proto3" json:"customerName,omitempty"`
	Dashboards           []*DataField `protobuf:"bytes,6,rep,name=dashboards,proto3" json:"dashboards,omitempty"`
	Applications         []*DataField `protobuf:"bytes,7,rep,name=applications,proto3" json:"applications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MasterDataResponse_Data) Reset()         { *m = MasterDataResponse_Data{} }
func (m *MasterDataResponse_Data) String() string { return proto.CompactTextString(m) }
func (*MasterDataResponse_Data) ProtoMessage()    {}
func (*MasterDataResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8, 0}
}

func (m *MasterDataResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterDataResponse_Data.Unmarshal(m, b)
}
func (m *MasterDataResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterDataResponse_Data.Marshal(b, m, deterministic)
}
func (m *MasterDataResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterDataResponse_Data.Merge(m, src)
}
func (m *MasterDataResponse_Data) XXX_Size() int {
	return xxx_messageInfo_MasterDataResponse_Data.Size(m)
}
func (m *MasterDataResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterDataResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_MasterDataResponse_Data proto.InternalMessageInfo

func (m *MasterDataResponse_Data) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MasterDataResponse_Data) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *MasterDataResponse_Data) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *MasterDataResponse_Data) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

func (m *MasterDataResponse_Data) GetDashboards() []*DataField {
	if m != nil {
		return m.Dashboards
	}
	return nil
}

func (m *MasterDataResponse_Data) GetApplications() []*DataField {
	if m != nil {
		return m.Applications
	}
	return nil
}

type ApplicationDataResponse struct {
	StatusCode           int32                         `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *ApplicationDataResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ApplicationDataResponse) Reset()         { *m = ApplicationDataResponse{} }
func (m *ApplicationDataResponse) String() string { return proto.CompactTextString(m) }
func (*ApplicationDataResponse) ProtoMessage()    {}
func (*ApplicationDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *ApplicationDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationDataResponse.Unmarshal(m, b)
}
func (m *ApplicationDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationDataResponse.Marshal(b, m, deterministic)
}
func (m *ApplicationDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationDataResponse.Merge(m, src)
}
func (m *ApplicationDataResponse) XXX_Size() int {
	return xxx_messageInfo_ApplicationDataResponse.Size(m)
}
func (m *ApplicationDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationDataResponse proto.InternalMessageInfo

func (m *ApplicationDataResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ApplicationDataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ApplicationDataResponse) GetData() *ApplicationDataResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type ApplicationDataResponse_Data struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns              []*Item      `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	RelatedRecords       []*DataField `protobuf:"bytes,3,rep,name=relatedRecords,proto3" json:"relatedRecords,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ApplicationDataResponse_Data) Reset()         { *m = ApplicationDataResponse_Data{} }
func (m *ApplicationDataResponse_Data) String() string { return proto.CompactTextString(m) }
func (*ApplicationDataResponse_Data) ProtoMessage()    {}
func (*ApplicationDataResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9, 0}
}

func (m *ApplicationDataResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationDataResponse_Data.Unmarshal(m, b)
}
func (m *ApplicationDataResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationDataResponse_Data.Marshal(b, m, deterministic)
}
func (m *ApplicationDataResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationDataResponse_Data.Merge(m, src)
}
func (m *ApplicationDataResponse_Data) XXX_Size() int {
	return xxx_messageInfo_ApplicationDataResponse_Data.Size(m)
}
func (m *ApplicationDataResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationDataResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationDataResponse_Data proto.InternalMessageInfo

func (m *ApplicationDataResponse_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApplicationDataResponse_Data) GetColumns() []*Item {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *ApplicationDataResponse_Data) GetRelatedRecords() []*DataField {
	if m != nil {
		return m.RelatedRecords
	}
	return nil
}

type ReferencedDataResponse struct {
	StatusCode           int32                        `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *ReferencedDataResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ReferencedDataResponse) Reset()         { *m = ReferencedDataResponse{} }
func (m *ReferencedDataResponse) String() string { return proto.CompactTextString(m) }
func (*ReferencedDataResponse) ProtoMessage()    {}
func (*ReferencedDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *ReferencedDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferencedDataResponse.Unmarshal(m, b)
}
func (m *ReferencedDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferencedDataResponse.Marshal(b, m, deterministic)
}
func (m *ReferencedDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferencedDataResponse.Merge(m, src)
}
func (m *ReferencedDataResponse) XXX_Size() int {
	return xxx_messageInfo_ReferencedDataResponse.Size(m)
}
func (m *ReferencedDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferencedDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReferencedDataResponse proto.InternalMessageInfo

func (m *ReferencedDataResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ReferencedDataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ReferencedDataResponse) GetData() *ReferencedDataResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReferencedDataResponse_Data struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns              []*Item  `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReferencedDataResponse_Data) Reset()         { *m = ReferencedDataResponse_Data{} }
func (m *ReferencedDataResponse_Data) String() string { return proto.CompactTextString(m) }
func (*ReferencedDataResponse_Data) ProtoMessage()    {}
func (*ReferencedDataResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10, 0}
}

func (m *ReferencedDataResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferencedDataResponse_Data.Unmarshal(m, b)
}
func (m *ReferencedDataResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferencedDataResponse_Data.Marshal(b, m, deterministic)
}
func (m *ReferencedDataResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferencedDataResponse_Data.Merge(m, src)
}
func (m *ReferencedDataResponse_Data) XXX_Size() int {
	return xxx_messageInfo_ReferencedDataResponse_Data.Size(m)
}
func (m *ReferencedDataResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferencedDataResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_ReferencedDataResponse_Data proto.InternalMessageInfo

func (m *ReferencedDataResponse_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReferencedDataResponse_Data) GetColumns() []*Item {
	if m != nil {
		return m.Columns
	}
	return nil
}

type ContentResponse struct {
	StatusCode           int32                 `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *ContentResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ContentResponse) Reset()         { *m = ContentResponse{} }
func (m *ContentResponse) String() string { return proto.CompactTextString(m) }
func (*ContentResponse) ProtoMessage()    {}
func (*ContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *ContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentResponse.Unmarshal(m, b)
}
func (m *ContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentResponse.Marshal(b, m, deterministic)
}
func (m *ContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentResponse.Merge(m, src)
}
func (m *ContentResponse) XXX_Size() int {
	return xxx_messageInfo_ContentResponse.Size(m)
}
func (m *ContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContentResponse proto.InternalMessageInfo

func (m *ContentResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ContentResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ContentResponse) GetData() *ContentResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type ContentResponse_Data struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rows                 []*Rows  `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentResponse_Data) Reset()         { *m = ContentResponse_Data{} }
func (m *ContentResponse_Data) String() string { return proto.CompactTextString(m) }
func (*ContentResponse_Data) ProtoMessage()    {}
func (*ContentResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11, 0}
}

func (m *ContentResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentResponse_Data.Unmarshal(m, b)
}
func (m *ContentResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentResponse_Data.Marshal(b, m, deterministic)
}
func (m *ContentResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentResponse_Data.Merge(m, src)
}
func (m *ContentResponse_Data) XXX_Size() int {
	return xxx_messageInfo_ContentResponse_Data.Size(m)
}
func (m *ContentResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_ContentResponse_Data proto.InternalMessageInfo

func (m *ContentResponse_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContentResponse_Data) GetRows() []*Rows {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestHeader)(nil), "applicationproto.RequestHeader")
	proto.RegisterType((*Item)(nil), "applicationproto.Item")
	proto.RegisterType((*DataField)(nil), "applicationproto.DataField")
	proto.RegisterType((*Rows)(nil), "applicationproto.Rows")
	proto.RegisterMapType((map[string]string)(nil), "applicationproto.Rows.RowEntry")
	proto.RegisterType((*MasterDataRequest)(nil), "applicationproto.MasterDataRequest")
	proto.RegisterType((*DataRequest)(nil), "applicationproto.DataRequest")
	proto.RegisterType((*ApplicationContentRequest)(nil), "applicationproto.ApplicationContentRequest")
	proto.RegisterType((*ReferencedContentRequest)(nil), "applicationproto.ReferencedContentRequest")
	proto.RegisterType((*MasterDataResponse)(nil), "applicationproto.MasterDataResponse")
	proto.RegisterType((*MasterDataResponse_Data)(nil), "applicationproto.MasterDataResponse.Data")
	proto.RegisterType((*ApplicationDataResponse)(nil), "applicationproto.ApplicationDataResponse")
	proto.RegisterType((*ApplicationDataResponse_Data)(nil), "applicationproto.ApplicationDataResponse.Data")
	proto.RegisterType((*ReferencedDataResponse)(nil), "applicationproto.ReferencedDataResponse")
	proto.RegisterType((*ReferencedDataResponse_Data)(nil), "applicationproto.ReferencedDataResponse.Data")
	proto.RegisterType((*ContentResponse)(nil), "applicationproto.ContentResponse")
	proto.RegisterType((*ContentResponse_Data)(nil), "applicationproto.ContentResponse.Data")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 739 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x6e, 0xd3, 0x48,
	0x14, 0x96, 0xe3, 0x24, 0x6d, 0x4f, 0xda, 0x6e, 0x7b, 0xd4, 0xed, 0x7a, 0xb3, 0x7f, 0x59, 0xef,
	0x82, 0xd2, 0x22, 0x22, 0x28, 0x12, 0xa0, 0x22, 0x84, 0x4a, 0xa1, 0x05, 0xa9, 0x20, 0xe1, 0xcb,
	0x0a, 0x21, 0x4d, 0xe3, 0xd3, 0xd6, 0xaa, 0xe3, 0x49, 0x67, 0xc6, 0xad, 0x72, 0xc3, 0x25, 0xe2,
	0x96, 0xe7, 0xe0, 0x61, 0x78, 0x08, 0x1e, 0x02, 0x2e, 0xd1, 0x4c, 0xec, 0xc4, 0x4e, 0x42, 0x12,
	0x44, 0x7a, 0x13, 0xf9, 0xfc, 0xcd, 0x39, 0xdf, 0x77, 0x7e, 0x02, 0x4b, 0x92, 0xc4, 0x45, 0xd0,
	0xa4, 0x46, 0x5b, 0x70, 0xc5, 0x71, 0x85, 0xb5, 0xdb, 0x61, 0xd0, 0x64, 0x2a, 0xe0, 0x91, 0xd1,
	0xb8, 0xd7, 0x60, 0xc9, 0xa3, 0xf3, 0x98, 0xa4, 0x7a, 0x46, 0xcc, 0x27, 0x81, 0x6b, 0x50, 0x52,
	0xfc, 0x8c, 0x22, 0xc7, 0xaa, 0x59, 0xf5, 0x05, 0xaf, 0x2b, 0xb8, 0xef, 0x2c, 0x28, 0x3e, 0x57,
	0xd4, 0xc2, 0x65, 0x28, 0x04, 0xbe, 0xb1, 0x95, 0xbc, 0x42, 0xe0, 0x23, 0x42, 0x31, 0x62, 0x2d,
	0x72, 0x0a, 0xc6, 0xdb, 0x7c, 0x63, 0x0d, 0x2a, 0x7e, 0x20, 0xdb, 0x21, 0xeb, 0xbc, 0xd4, 0x26,
	0xdb, 0x98, 0xb2, 0x2a, 0xfc, 0x13, 0x16, 0x58, 0x18, 0x9c, 0x44, 0x2d, 0x8a, 0x94, 0x53, 0x34,
	0xf6, 0xbe, 0x02, 0xab, 0x30, 0x2f, 0xb9, 0x50, 0xec, 0x28, 0x24, 0xa7, 0x54, 0xb3, 0xea, 0xf3,
	0x5e, 0x4f, 0x76, 0x5f, 0xc1, 0xc2, 0x13, 0xa6, 0xd8, 0x5e, 0x40, 0xa1, 0x3f, 0x75, 0x31, 0x24,
	0x9b, 0x22, 0x68, 0x6b, 0xd0, 0xbd, 0x62, 0xfa, 0x2a, 0xf7, 0x1c, 0x8a, 0x1e, 0xbf, 0x94, 0x78,
	0x1b, 0x6c, 0x8f, 0x5f, 0x3a, 0x56, 0xcd, 0xae, 0x57, 0xb6, 0xfe, 0x69, 0x0c, 0x52, 0xd5, 0xd0,
	0x4e, 0xfa, 0xe7, 0x69, 0xa4, 0x44, 0xc7, 0xd3, 0xbe, 0xd5, 0xbb, 0x30, 0x9f, 0x2a, 0x70, 0x05,
	0xec, 0x33, 0xea, 0x24, 0xb4, 0xe9, 0x4f, 0x4d, 0xe5, 0x05, 0x0b, 0xe3, 0xb4, 0x9e, 0xae, 0xb0,
	0x5d, 0xb8, 0x6f, 0xb9, 0x07, 0xb0, 0xfa, 0x82, 0x49, 0x45, 0x42, 0x63, 0x49, 0xf8, 0xc7, 0x7b,
	0x50, 0x3e, 0x35, 0x3d, 0x30, 0x6f, 0x8c, 0x2e, 0x21, 0xdb, 0x2a, 0x2f, 0x71, 0x77, 0x0f, 0xa1,
	0x32, 0x8b, 0x77, 0x46, 0xd1, 0xe7, 0xbe, 0x85, 0xdf, 0x77, 0xfa, 0xd1, 0xbb, 0x3c, 0x52, 0x14,
	0xa9, 0xab, 0xc8, 0xa4, 0xd9, 0x3a, 0x8f, 0x49, 0x74, 0x92, 0x16, 0x75, 0x05, 0xb7, 0x03, 0x8e,
	0x47, 0xc7, 0x24, 0x28, 0x6a, 0x92, 0x7f, 0x95, 0xe9, 0x57, 0xc0, 0x0e, 0x7c, 0xe9, 0xd8, 0x35,
	0xbb, 0x5e, 0xf2, 0xf4, 0xa7, 0xfb, 0xde, 0x06, 0xcc, 0x76, 0x49, 0xb6, 0x79, 0x24, 0x09, 0xff,
	0x06, 0x90, 0x8a, 0xa9, 0x58, 0xee, 0x72, 0x9f, 0x92, 0xe1, 0xcb, 0x68, 0xd0, 0x81, 0xb9, 0x16,
	0x49, 0xc9, 0x4e, 0xd2, 0xf7, 0x53, 0x11, 0x1f, 0x42, 0xd1, 0x67, 0x8a, 0x19, 0x80, 0x95, 0xad,
	0x8d, 0xe1, 0x6a, 0x87, 0xb3, 0x35, 0x8c, 0x60, 0xc2, 0xaa, 0x5f, 0x2d, 0x28, 0x6a, 0x51, 0xef,
	0x47, 0x2c, 0x49, 0x64, 0x20, 0xf4, 0x64, 0x5c, 0x87, 0x32, 0xbb, 0x60, 0x8a, 0x89, 0x84, 0xc6,
	0x44, 0xd2, 0x31, 0xc7, 0x71, 0x18, 0x9a, 0x85, 0xec, 0x2e, 0x5c, 0x4f, 0x46, 0x17, 0x16, 0x9b,
	0xb1, 0x54, 0xbc, 0x45, 0xc2, 0xd8, 0x4b, 0xc6, 0x9e, 0xd3, 0xe1, 0x03, 0x00, 0x9f, 0xc9, 0xd3,
	0x23, 0xce, 0x84, 0x2f, 0x9d, 0xb2, 0xd9, 0x91, 0x3f, 0x86, 0x11, 0xf4, 0x76, 0xd3, 0xcb, 0xb8,
	0xe3, 0x23, 0x58, 0xcc, 0x78, 0x4a, 0x67, 0x6e, 0x72, 0x78, 0x2e, 0xc0, 0xfd, 0x58, 0x80, 0xdf,
	0x32, 0x63, 0x38, 0xa3, 0x7e, 0x3c, 0xce, 0xf5, 0xa3, 0x31, 0x5c, 0xce, 0x77, 0x52, 0x66, 0x9b,
	0xf2, 0x21, 0x6d, 0x4a, 0x3a, 0x53, 0x56, 0x66, 0xa6, 0x6e, 0xc1, 0x5c, 0x93, 0x87, 0x71, 0x2b,
	0x92, 0x4e, 0xc1, 0x40, 0x5e, 0x1f, 0xce, 0xa1, 0xaf, 0xaa, 0x97, 0xba, 0xe1, 0x2e, 0x2c, 0x0b,
	0x0a, 0x99, 0x22, 0xdf, 0xa3, 0x26, 0x17, 0xc9, 0x40, 0x4e, 0xe0, 0x6a, 0x20, 0xc4, 0xfd, 0x6c,
	0xc1, 0x7a, 0x7f, 0x69, 0x66, 0x44, 0xd6, 0x4e, 0x8e, 0xac, 0x9b, 0xa3, 0x56, 0x6d, 0x54, 0xc6,
	0x2c, 0x57, 0x07, 0xb3, 0xa4, 0xca, 0xfd, 0x64, 0xc1, 0x2f, 0xbd, 0x83, 0xf0, 0xd3, 0xf0, 0xb6,
	0x73, 0xf0, 0xae, 0x0f, 0x27, 0x1f, 0x48, 0x95, 0xc5, 0xb5, 0x37, 0x06, 0xd7, 0x26, 0x14, 0x05,
	0xbf, 0x1c, 0x03, 0x4a, 0xff, 0xab, 0x78, 0xc6, 0x67, 0xeb, 0x8b, 0x0d, 0x95, 0xcc, 0xc8, 0xe1,
	0x21, 0x2c, 0xed, 0x93, 0xea, 0x1f, 0x05, 0xfc, 0x6f, 0xfc, 0xc9, 0x30, 0xa7, 0xae, 0xfa, 0xff,
	0x34, 0x77, 0x05, 0xdf, 0x00, 0xee, 0x93, 0x1a, 0x18, 0x70, 0xfc, 0x6b, 0xf4, 0x98, 0xa5, 0x4f,
	0x6f, 0x4c, 0xbd, 0x22, 0xf8, 0x1a, 0x56, 0xf7, 0x49, 0xe5, 0x67, 0x62, 0xd2, 0xf3, 0xf5, 0x69,
	0x87, 0x0a, 0x4f, 0xe0, 0xd7, 0x7c, 0xf5, 0x49, 0x77, 0xf0, 0xc6, 0xd8, 0x0a, 0xf3, 0xff, 0x1f,
	0xd5, 0x7f, 0x27, 0x76, 0x19, 0x09, 0xd6, 0x72, 0x30, 0xd2, 0x3c, 0x9b, 0xe3, 0x4a, 0xfd, 0xe1,
	0x34, 0x47, 0x65, 0xa3, 0xbe, 0xf3, 0x2d, 0x00, 0x00, 0xff, 0xff, 0x36, 0x63, 0x34, 0x7d, 0xaf,
	0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApplicationClient is the client API for Application service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApplicationClient interface {
	GetMasterData(ctx context.Context, in *MasterDataRequest, opts ...grpc.CallOption) (*MasterDataResponse, error)
	GetApplicationData(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*ApplicationDataResponse, error)
	GetReferencedData(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*ReferencedDataResponse, error)
	GetApplicationContent(ctx context.Context, in *ApplicationContentRequest, opts ...grpc.CallOption) (*ContentResponse, error)
	GetReferencedContent(ctx context.Context, in *ReferencedContentRequest, opts ...grpc.CallOption) (*ContentResponse, error)
}

type applicationClient struct {
	cc *grpc.ClientConn
}

func NewApplicationClient(cc *grpc.ClientConn) ApplicationClient {
	return &applicationClient{cc}
}

func (c *applicationClient) GetMasterData(ctx context.Context, in *MasterDataRequest, opts ...grpc.CallOption) (*MasterDataResponse, error) {
	out := new(MasterDataResponse)
	err := c.cc.Invoke(ctx, "/applicationproto.Application/GetMasterData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) GetApplicationData(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*ApplicationDataResponse, error) {
	out := new(ApplicationDataResponse)
	err := c.cc.Invoke(ctx, "/applicationproto.Application/GetApplicationData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) GetReferencedData(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*ReferencedDataResponse, error) {
	out := new(ReferencedDataResponse)
	err := c.cc.Invoke(ctx, "/applicationproto.Application/GetReferencedData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) GetApplicationContent(ctx context.Context, in *ApplicationContentRequest, opts ...grpc.CallOption) (*ContentResponse, error) {
	out := new(ContentResponse)
	err := c.cc.Invoke(ctx, "/applicationproto.Application/GetApplicationContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) GetReferencedContent(ctx context.Context, in *ReferencedContentRequest, opts ...grpc.CallOption) (*ContentResponse, error) {
	out := new(ContentResponse)
	err := c.cc.Invoke(ctx, "/applicationproto.Application/GetReferencedContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicationServer is the server API for Application service.
type ApplicationServer interface {
	GetMasterData(context.Context, *MasterDataRequest) (*MasterDataResponse, error)
	GetApplicationData(context.Context, *DataRequest) (*ApplicationDataResponse, error)
	GetReferencedData(context.Context, *DataRequest) (*ReferencedDataResponse, error)
	GetApplicationContent(context.Context, *ApplicationContentRequest) (*ContentResponse, error)
	GetReferencedContent(context.Context, *ReferencedContentRequest) (*ContentResponse, error)
}

// UnimplementedApplicationServer can be embedded to have forward compatible implementations.
type UnimplementedApplicationServer struct {
}

func (*UnimplementedApplicationServer) GetMasterData(ctx context.Context, req *MasterDataRequest) (*MasterDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMasterData not implemented")
}
func (*UnimplementedApplicationServer) GetApplicationData(ctx context.Context, req *DataRequest) (*ApplicationDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplicationData not implemented")
}
func (*UnimplementedApplicationServer) GetReferencedData(ctx context.Context, req *DataRequest) (*ReferencedDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReferencedData not implemented")
}
func (*UnimplementedApplicationServer) GetApplicationContent(ctx context.Context, req *ApplicationContentRequest) (*ContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplicationContent not implemented")
}
func (*UnimplementedApplicationServer) GetReferencedContent(ctx context.Context, req *ReferencedContentRequest) (*ContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReferencedContent not implemented")
}

func RegisterApplicationServer(s *grpc.Server, srv ApplicationServer) {
	s.RegisterService(&_Application_serviceDesc, srv)
}

func _Application_GetMasterData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MasterDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).GetMasterData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/applicationproto.Application/GetMasterData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).GetMasterData(ctx, req.(*MasterDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_GetApplicationData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).GetApplicationData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/applicationproto.Application/GetApplicationData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).GetApplicationData(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_GetReferencedData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).GetReferencedData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/applicationproto.Application/GetReferencedData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).GetReferencedData(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_GetApplicationContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).GetApplicationContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/applicationproto.Application/GetApplicationContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).GetApplicationContent(ctx, req.(*ApplicationContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_GetReferencedContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReferencedContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).GetReferencedContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/applicationproto.Application/GetReferencedContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).GetReferencedContent(ctx, req.(*ReferencedContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Application_serviceDesc = grpc.ServiceDesc{
	ServiceName: "applicationproto.Application",
	HandlerType: (*ApplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMasterData",
			Handler:    _Application_GetMasterData_Handler,
		},
		{
			MethodName: "GetApplicationData",
			Handler:    _Application_GetApplicationData_Handler,
		},
		{
			MethodName: "GetReferencedData",
			Handler:    _Application_GetReferencedData_Handler,
		},
		{
			MethodName: "GetApplicationContent",
			Handler:    _Application_GetApplicationContent_Handler,
		},
		{
			MethodName: "GetReferencedContent",
			Handler:    _Application_GetReferencedContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
